steelbrain/node-ssh

- Source/SSH.js
- package.json
Beep Boop
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/steelbrain/node-ssh/15)
> Escape parameters

- package.json
- spec/main-spec.js
- spec/ssh-server.js
- src/helpers.js
- src/index.js
> Implement mkdirp in sftp

- README.md
- spec/main-spec.js
- src/index.js
Ref https://github.com/steelbrain/node-ssh/issues/46#issuecomment-265430246
> Add maxAtOnce to putFiles()

- spec/main-spec.js
- src/index.js
Apparently we had a spec but it was failing
> Add retry to sftp mkdir

- CHANGELOG.md
- spec/helpers-spec.js
- src/helpers.js
> Cleanup and add specs

- README.md
- src/index.js
no issue
- sftp supports options e.g. opts.step to receive a progress of a downloaded or uploaded file
> ✨  getFile/putFile with options

- CHANGELOG.md
- README.md
- src/index.js
> Add options support in exec

- spec/main-spec.js
- src/index.js
As advertised. Thanks for the report @joneal
> Fix sftp mkdir for long paths

- CHANGELOG.md
- README.md
- spec/fixtures/test-program.js
- spec/main-spec.js
- src/index.js
> Add stream callbacks to exec{,Command}

- README.md
- src/helpers.js
- src/index.js
To fix the following issue: https://github.com/mscdex/ssh2/issues/604
> Allow to use keyboard-interactive user authentication and set "keyboard-interactive" connection event

- README.md
As to the designation of the port number, since it was not mention, I added it.
> Add port option to README

- README.md
- src/helpers.js
1) helpers.js: fix a condition in normalizeConfig which was always setting user-defined onKeyboardInteractive callback to null.
2) README.md: fix an example.
> Fix keyboard interactive

- src/index.js
> Fix error message on bad remoteDirectory value

- .babelrc
- .circleci/config.yml
- package-lock.json
- package.json
- spec/.eslintrc.json
- spec/helpers-spec.js
- spec/helpers.js
- spec/main-spec.js
- spec/ssh-server.js
- src/helpers.js
- src/index.js
- src/types.js
- Upgrades all dependencies
- Use `ava` for testing, Instead of AtomIO `apm`
- Add CircleCI v2 config
- Upgrade to Babel v7
> Package maintenance

- src/index.js
> Stop swallowing non-existent cwd errors

- CHANGELOG.md
- src/index.ts
Thanks to @mbr4477 for reporting and investigating
Fixes https://github.com/steelbrain/node-ssh/issues/300
> Fix unixification of paths on Windows

- src/index.ts
- test/main-test.ts
- test/ssh-server.ts
- test/validation-test.ts
I've exported all interfaces, types and classes that should be visible from the outside.
This will help Typescript developers by providing typings for most of function inputs.
> Export types/classes/interfaces for Typescript typing

- CHANGELOG.md
- README.md
- src/index.ts
Fixes https://github.com/steelbrain/node-ssh/issues/331
> Add options to {with,request}Shell

- CHANGELOG.md
- LICENSE.md
- README.md
- package.json
- src/index.ts
- yarn.lock
> Add support for Readable stream in stdin

- package.json
- test/ssh-server.ts
- yarn.lock
> Upgrade to node-ssh v1

- src/index.ts
Hi @steelbrain please check this solution to #399
> #399 Added Promise rejection on error event.

- CHANGELOG.md
- package.json
- src/index.ts
Followup to https://github.com/steelbrain/node-ssh/pull/417
Potentially fixes https://github.com/steelbrain/node-ssh/issues/399
> Experimental fix for app crashes
